//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dot.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dot.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换换行符为LF.
        /// </summary>
        public static string ConvertEndOfLineToLF {
            get {
                return ResourceManager.GetString("ConvertEndOfLineToLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}（已复制到剪贴板）.
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件通配符.
        /// </summary>
        public static string FileSearchPattern {
            get {
                return ResourceManager.GetString("FileSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要处理的目录路径.
        /// </summary>
        public static string FolderPath {
            get {
                return ResourceManager.GetString("FolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID工具.
        /// </summary>
        public static string GuidTool {
            get {
                return ResourceManager.GetString("GuidTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本编码工具.
        /// </summary>
        public static string HelpForText {
            get {
                return ResourceManager.GetString("HelpForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入文本为空.
        /// </summary>
        public static string InputTextIsEmpty {
            get {
                return ResourceManager.GetString("InputTextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接NTP服务器: {0} &lt;{1}&gt; ... .
        /// </summary>
        public static string Main_GetUtc_ {
            get {
                return ResourceManager.GetString("Main_GetUtc_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ms.
        /// </summary>
        public static string Main_GetUtc__0_us {
            get {
                return ResourceManager.GetString("Main_GetUtc__0_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送请求... .
        /// </summary>
        public static string Main_GetUtc_sdf {
            get {
                return ResourceManager.GetString("Main_GetUtc_sdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接收数据... .
        /// </summary>
        public static string Main_GetUtc_接收请求___ {
            get {
                return ResourceManager.GetString("Main_GetUtc_接收请求___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTP服务器时间: {0}.
        /// </summary>
        public static string Main_Run_NTP服务器时间___0_ {
            get {
                return ResourceManager.GetString("Main_Run_NTP服务器时间___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按&quot;y&quot;同步系统时钟, 其它按键退出程序.
        /// </summary>
        public static string Main_Run_SyncClock {
            get {
                return ResourceManager.GetString("Main_Run_SyncClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步完成, 开始复检....
        /// </summary>
        public static string Main_Run_SyncDone {
            get {
                return ResourceManager.GetString("Main_Run_SyncDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地时钟快: {0} ms.
        /// </summary>
        public static string Main_Run_时差___0__ms {
            get {
                return ResourceManager.GetString("Main_Run_时差___0__ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地时钟慢: {0} ms.
        /// </summary>
        public static string Main_Run_时差___1__ms {
            get {
                return ResourceManager.GetString("Main_Run_时差___1__ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地时间: {0}.
        /// </summary>
        public static string Main_Run_本地时间___0_ {
            get {
                return ResourceManager.GetString("Main_Run_本地时间___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有需要处理的文件.
        /// </summary>
        public static string NoFileToBeProcessed {
            get {
                return ResourceManager.GetString("NoFileToBeProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有服务均不可用.
        /// </summary>
        public static string NoService {
            get {
                return ResourceManager.GetString("NoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定的路径“{0}”不存在.
        /// </summary>
        public static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按下任意键继续....
        /// </summary>
        public static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitSet 1：[0-9]，2：[a-z]，4：[A-Z]，8：[ascii.0x21-0x2F].
        /// </summary>
        public static string PwdGenerateTypes {
            get {
                return ResourceManager.GetString("PwdGenerateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码长度.
        /// </summary>
        public static string PwdLength {
            get {
                return ResourceManager.GetString("PwdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随机密码生成器.
        /// </summary>
        public static string RandomPasswordGenerator {
            get {
                return ResourceManager.GetString("RandomPasswordGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只读模式（仅做测试，不实际修改）.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除文件尾部换行和空格.
        /// </summary>
        public static string RemoveTrailingWhiteSpaces {
            get {
                return ResourceManager.GetString("RemoveTrailingWhiteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找文件....
        /// </summary>
        public static string SearchingFile {
            get {
                return ResourceManager.GetString("SearchingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 个文件.
        /// </summary>
        public static string SearchingFileOK {
            get {
                return ResourceManager.GetString("SearchingFileOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已读取：{0}/{1}，处理：{2}，跳过：{3}.
        /// </summary>
        public static string ShowMessageTemp {
            get {
                return ResourceManager.GetString("ShowMessageTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要处理的文本（默认取取剪贴板值）.
        /// </summary>
        public static string TextTobeProcessed {
            get {
                return ResourceManager.GetString("TextTobeProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超时.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除文件的uf8 bom.
        /// </summary>
        public static string TrimUtf8Bom {
            get {
                return ResourceManager.GetString("TrimUtf8Bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用大写输出.
        /// </summary>
        public static string UseUppercase {
            get {
                return ResourceManager.GetString("UseUppercase", resourceCulture);
            }
        }
    }
}