# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "tk" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 从仓库拉取代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          filter: tree:0
      - name: 安装 DOTNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: 发布 .net8-windows@win-x64
        working-directory: ./src/backend/Dot
        run: dotnet publish Dot.csproj -f net8.0-windows -r win-x64 -c Release
